name: CI Build
on:
  push:
  workflow_dispatch:
  release:
    types: [created, edited]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=bin

    - name: Build
      run: cmake --build build

    - name: Get binary name
      id: binary_name
      run: python .github/workflows/find_binary.py

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.binary_name.outputs.binary_filename_os }}
        path: ${{ steps.binary_name.outputs.binary_abs_path }}
    
    - name: Upload binary as release asset
      if: ${{ github.event_name == 'release' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.binary_name.outputs.binary_abs_path }}
        asset_name: ${{ steps.binary_name.outputs.binary_filename_os }}
        asset_content_type: application/octet-stream