name: CI Build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=bin

    - name: Build
      run: cmake --build build

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: goo_format_analyzer_for_${{ matrix.os }}
        path: build/bin